version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: db-ittoku-tech
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    container_name: api-ittoku-tech
    build: ./api/
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/api
    depends_on:
      - db

  web:
    container_name: blog-ittoku-tech
    build: ./blog/
    ports:
      - "3000:3000"
    volumes:
      - ./blog:/web
