version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: db-ittoku-tech-test
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    container_name: api-ittoku-tech-test
    build: 
      context: ./api
      dockerfile: "Dockerfile.dev"
    environment:
      RAILS_ENV: test
      DOMAIN: api.ittoku-tech.com
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/api
    depends_on:
      - db

  web:
    container_name: blog-ittoku-tech-test
    build: 
      context: ./blog
      dockerfile: "Dockerfile.dev"
    environment:
      NODE_ENV: test
      DOMAIN: blog.ittoku-tech.com
    ports:
      - "8080:8080"
    volumes:
      - ./blog:/web
    depends_on:
      - api
